In [1]:
import pandas as pd
import numpy as np

###Tratando dados nulos

In [2]:
utf = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'

df = pd.read_csv(utf, sep=';')
df

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [3]:
df.isnull() #True -> dados nulos e False -> dados não nulos

        Tipo  Bairro  Quartos  Vagas  Suites   Area  Valor  Condominio   IPTU
0      False   False    False  False   False  False  False       False  False
1      False   False    False  False   False  False  False        True   True
2      False   False    False  False   False  False  False       False  False
3      False   False    False  False   False  False  False       False  False
4      False   False    False  False   False  False  False       False   True
...      ...     ...      ...    ...     ...    ...    ...         ...    ...
32955  False   False    False  False   False  False  False       False  False
32956  False   False    False  False   False  False  False       False  False
32957  False   False    False  False   False  False  False       False  False
32958  False   False    False  False   False  False  False       False   True
32959  False   False    False  False   False  False  False       False  False

[32960 rows x 9 columns]

In [4]:
df.isnull().sum() #Soma a quantidade de dados nulos existentes True = 1 e False = 0

Tipo              0
Bairro            0
Quartos           0
Vagas             0
Suites            0
Area              0
Valor            17
Condominio     4093
IPTU          10237
dtype: int64

In [5]:
df.fillna(0)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [6]:
df = df.fillna(0)

In [7]:
df.isnull().sum()

Tipo          0
Bairro        0
Quartos       0
Vagas         0
Suites        0
Area          0
Valor         0
Condominio    0
IPTU          0
dtype: int64

Existem diversas formas de tratar dados nulos com o Pandas. Algumas das principais formas são:

    -> Remover os dados nulos: É possível remover as linhas ou colunas que possuem valores nulos utilizando o método dropna() . Esse método remove todas as linhas ou colunas que possuem pelo menos um valor nulo.

    -> Preencher os dados nulos: Utilizando o método fillna(), podemos preencher os valores nulos com um valor específico. Além disso, também é possível utilizar argumentos específicos do método fillna() como o method=”ffill” ou method=”bfill” para preencher os valores nulos com o valor anterior ou posterior, respectivamente.

    -> Interpolar os dados nulos: É possível utilizar o método interpolate() para preencher os valores nulos com valores interpolados, ou seja, valores calculados a partir dos valores vizinhos.

###Removendo registros

In [8]:
df.query('Valor == 0 | Condominio == 0' )

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,0.0,0.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0
10,Apartamento,Centro,1,0,0,36,1200.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
32914,Loja/Salão,Campo Grande,0,0,0,160,2650.0,0.0,0.0
32928,Loja/Salão,Leblon,0,0,0,68,25000.0,0.0,1113.0
32929,Loja/Salão,Freguesia (Jacarepaguá),0,0,0,80,5800.0,0.0,215.0
32931,Casa,Centro,5,0,1,160,5000.0,0.0,80.0
32954,Box/Garagem,Centro,0,0,0,755,14000.0,0.0,0.0

In [9]:
df.query('Valor == 0 | Condominio == 0').index

Index([    1,     5,     7,     8,    10,    16,    18,    31,    35,    76,
       ...
       32893, 32897, 32899, 32911, 32912, 32914, 32928, 32929, 32931, 32954],
      dtype='int64', length=4106)

In [10]:
registro_remover = df.query('Valor == 0 | Condominio == 0').index

In [11]:
df.drop(registro_remover, axis=0, inplace=True)

In [12]:
df.query('Valor == 0 | Condominio == 0')

Empty DataFrame
Columns: [Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU]
Index: []

In [13]:
df.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0

In [14]:
df.drop('Tipo', axis = 1, inplace=True)

In [15]:
df.head()

            Bairro  Quartos  Vagas  Suites  Area   Valor  Condominio    IPTU
0       Copacabana        1      0       0    40  1700.0       500.0    60.0
2  Barra da Tijuca        0      4       0   150  5200.0      4020.0  1111.0
3           Centro        1      0       0    15   800.0       390.0    20.0
4     Higienópolis        1      0       0    48   800.0       230.0     0.0
6         Cachambi        2      0       0    50  1300.0       301.0    17.0

###Aplicando filtros

In [18]:
#Apartamento que possuem 1 quarto e aluguel menor que 1200
quartos_1_aluguel_menos = (df['Quartos'] == 1) & (df['Valor'] < 1200)
df[quartos_1_aluguel_menos]

             Bairro  Quartos  Vagas  Suites  Area   Valor  Condominio   IPTU
3            Centro        1      0       0    15   800.0       390.0   20.0
4      Higienópolis        1      0       0    48   800.0       230.0    0.0
28           Tijuca        1      0       0    48   750.0       772.0   25.0
54           Centro        1      0       0    27   750.0       371.0   19.0
94           Centro        1      1       0    37  1100.0       540.0  900.0
...             ...      ...    ...     ...   ...     ...         ...    ...
32714      Botafogo        1      0       0    21  1000.0       282.0   25.0
32763        Glória        1      0       0    10   400.0       107.0   10.0
32818      Flamengo        1      0       0    23   900.0       605.0    0.0
32844        Centro        1      0       0    24  1100.0       323.0    0.0
32950        Tijuca        1      0       0    28  1000.0       360.0   25.0

[835 rows x 8 columns]

In [21]:
df = pd.read_csv(utf, sep=';')
df

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [23]:
#Apartamento que possuem pelo menos 2 quartos, aluguel menor que 3000 e area maior que 70
apartamento_2q_m3000_a70 = (df['Tipo'] == 'Apartamento') & (df['Quartos'] == 2) & (df['Valor'] < 3000) & (df['Area'] > 70)
df[apartamento_2q_m3000_a70]

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
21,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
24,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
32,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
57,Apartamento,Recreio dos Bandeirantes,2,1,2,83,1600.0,1160.0,157.0
67,Apartamento,Maracanã,2,0,0,86,1800.0,600.0,82.0
...,...,...,...,...,...,...,...,...,...
32881,Apartamento,Taquara,2,1,1,71,1300.0,470.0,NaN
32890,Apartamento,Freguesia (Jacarepaguá),2,1,1,87,1300.0,869.0,77.0
32933,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
32934,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
32940,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0

In [24]:
df.to_csv('dados_apartamento.csv')

In [25]:
df2 = pd.read_csv('dados_apartamento.csv')
df2

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32955,32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [28]:
df.to_csv('dados_apartamento.csv', index=False, sep=';')

In [29]:
df2 = pd.read_csv('dados_apartamento.csv')
df2

      Tipo;Bairro;Quartos;Vagas;Suites;Area;Valor;Condominio;IPTU
0        Quitinete;Copacabana;1;0;0;40;1700.0;500.0;60.0
1                Casa;Jardim Botânico;2;0;1;100;7000.0;;
2      Conjunto Comercial/Sala;Barra da Tijuca;0;4;0;...
3           Apartamento;Centro;1;0;0;15;800.0;390.0;20.0
4         Apartamento;Higienópolis;1;0;0;48;800.0;230.0;
...                                                  ...
32955         Quitinete;Centro;0;0;0;27;800.0;350.0;25.0
32956  Apartamento;Jacarepaguá;3;1;2;78;1800.0;800.0;...
32957  Apartamento;São Francisco Xavier;2;1;0;48;1400...
32958          Apartamento;Leblon;2;0;0;70;3000.0;760.0;
32959  Conjunto Comercial/Sala;Centro;0;0;0;250;6500....

[32960 rows x 1 columns]

In [31]:
df2 = pd.read_csv('dados_apartamento.csv', sep=';')
df2

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

O Pandas oferece diversos métodos para salvar arquivos em diferentes formatos. Alguns exemplos são:

    to_csv(): salva o DataFrame em um arquivo CSV (Comma-Separated Values);

    to_excel(): salva o DataFrame em um arquivo Excel;

    to_json(): salva o DataFrame em um arquivo JSON (JavaScript Object Notation).

###Exercício

In [85]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
df_alunos = pd.read_csv(url)
df_alunos

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [86]:
#1) Verifique se a base de dados possui dados nulos e, caso tenha, realize o tratamento desses dados nulos da forma que achar mais coerente com a situação.
df_alunos.isnull

<bound method DataFrame.isnull of          Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True>

In [87]:
df_alunos.isnull().sum()

Nome        0
Idade       0
Notas       6
Aprovado    0
dtype: int64

In [88]:
df_alunos = df_alunos.fillna(0)
df_alunos

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [89]:
nomes_removidos = df_alunos.query('Nome == "Alice" | Nome == "Carlos"').index
df_alunos.drop(nomes_removidos, axis=0, inplace=True)
df_alunos

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [90]:
df_alunos.replace()

/tmp/ipykernel_18538/3280496038.py:1: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df_alunos.replace()

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [91]:
#3) Aplique um filtro que selecione apenas os alunos que foram aprovados.
alunos_aprovados = (df_alunos['Aprovado'] == True)
alunos_aprovados = df_alunos[alunos_aprovados]

In [92]:
#alunos_aprovados = df_alunos['Aprovado'] == True
#df_alunos[alunos_aprovados]
#alunos_aprovados = df_alunos[alunos_aprovados]

In [93]:
alunos_aprovados = alunos_aprovados.replace(7.0, 8.0)

In [94]:
#4) Salve o DataFrame que possui apenas os alunos aprovados em um arquivo csv chamado "alunos_aprovados.csv"
alunos_aprovados.to_csv('alunos_aprovados.csv', index=False, sep=';')

In [95]:
df_alunos_aprovados = pd.read_csv('alunos_aprovados.csv', sep=';')
df_alunos_aprovados

        Nome  Idade  Notas  Aprovado
0        Ary     20    7.5      True
1       Beto     21   10.0      True
2       Dara     21    8.0      True
3  Sthefanie     26    9.5      True
4      Mirla     25    9.0      True
5     Mylena     29    8.0      True
6      Nadia     34    8.0      True

Nessa aula, você aprendeu a:

    -> Verificar se uma base de dados possui dados nulos;
    -> Tratar os dados nulos;
    -> Remover linhas e colunas de um DataFrame;
    -> Realizar diferentes seleções em uma base de dados;
    -> Salvar dados no formato csv;
    -> Utilizar o método replace para substituir valores em uma base de dados.