In [1]:
import pandas as pd

In [2]:
utf = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'

df = pd.read_csv(utf, sep=';')
df

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [6]:
#Criando colunas numéricas
df['Valor_por_mes'] = df['Valor'] + df['Condominio']
df.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor_por_mes
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2200.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,9220.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1190.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN,1030.0

In [7]:
df['Valor_por_ano'] = (df['Valor_por_mes'] * 12) + df['IPTU']
df

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor_por_mes,Valor_por_ano
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2200.0,26460.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,9220.0,111751.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1190.0,14300.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN,1030.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0,1150.0,13825.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0,2600.0,31240.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0,1909.0,22945.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN,3760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0,10706.0,129581.0

In [15]:
#Criando colunas categóricas
df['Descricao'] =  df['Tipo'] + ' em ' + df['Bairro'] + ' com ' + \
                    df['Quartos'].astype(str) + ' quarto(s) ' + \
                    ' e ' + df['Vagas'].astype(str) + ' vaga(s) de garagem.'
df.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor_por_mes,Valor_por_ano,Descricao
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2200.0,26460.0,Quitinete em Copacabana com 1 quarto(s) e 0 v...
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN,NaN,NaN,Casa em Jardim Botânico com 2 quarto(s) e 0 v...
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,9220.0,111751.0,Conjunto Comercial/Sala em Barra da Tijuca com...
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1190.0,14300.0,Apartamento em Centro com 1 quarto(s) e 0 vag...
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN,1030.0,NaN,Apartamento em Higienópolis com 1 quarto(s) e...

In [17]:
df['Possui_suite'] = df['Suites'].apply(lambda x: 'Sim' if x > 0 else 'Não')
df.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor_por_mes,Valor_por_ano,Descricao,Possui_suite
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2200.0,26460.0,Quitinete em Copacabana com 1 quarto(s) e 0 v...,Não
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN,NaN,NaN,Casa em Jardim Botânico com 2 quarto(s) e 0 v...,Sim
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,9220.0,111751.0,Conjunto Comercial/Sala em Barra da Tijuca com...,Não
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1190.0,14300.0,Apartamento em Centro com 1 quarto(s) e 0 vag...,Não
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN,1030.0,NaN,Apartamento em Higienópolis com 1 quarto(s) e...,Não

In [18]:
df.to_csv('dados_completos_dev.csv', index=False, sep=';')

Existem diversas maneiras de criar colunas em um DataFrame no Pandas:

    -> Atribuição direta de valores a uma nova coluna:
    df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
    df['C'] = [7, 8, 9]

    -> Criação de uma coluna a partir de operações entre outras colunas:
    df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
    df['C'] = df['A'] + df['B']

    -> Utilização do método assign() para criar uma nova coluna:
    df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
    df = df.assign(C=[7, 8, 9])

    -> Utilização do método apply() para aplicar uma função a uma coluna existente e criar uma nova coluna:
    df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
    df['C'] = df['A'].apply(lambda x: x * 2)

###Exercício

In [20]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
df_alunos = pd.read_csv(url)
df_alunos

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [24]:
#1) Os alunos participaram de uma atividade extracurricular e ganharam pontos extras. Esses pontos extras correspondem a 40% da nota atual de cada um deles. Com base nisso, crie uma coluna chamada "Pontos_extras" que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles.
df_alunos['Pontos_extras'] = df_alunos['Notas'] * 0.4
df_alunos

         Nome  Idade  Notas  Aprovado  Pontos_extras
0         Ary     20    7.5      True           3.00
1         Ana     18    NaN     False            NaN
2       Cátia     27    2.5     False           1.00
3       Denis     18    5.0     False           2.00
4        Beto     21   10.0      True           4.00
5       Bruna     23    NaN     False            NaN
6        Dara     21    7.0      True           2.80
7      Carlos     19    6.0      True           2.40
8       Alice     35    5.6     False           2.24
9       Vitor     28    NaN     False            NaN
10     Daniel     21    NaN     False            NaN
11       Igor     24    4.5     False           1.80
12  Sthefanie     26    9.5      True           3.80
13      Mirla     25    9.0      True           3.60
14      Paulo     37    NaN     False            NaN
15     Mylena     29    7.0      True           2.80
16      Lucas     33    NaN     False            NaN
17      Nadia     34    8.0      True           3.20

In [26]:
#2) Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras.
df_alunos['Notas_finais'] = df_alunos['Notas'] + df_alunos['Pontos_extras']
df_alunos

         Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais
0         Ary     20    7.5      True           3.00         10.50
1         Ana     18    NaN     False            NaN           NaN
2       Cátia     27    2.5     False           1.00          3.50
3       Denis     18    5.0     False           2.00          7.00
4        Beto     21   10.0      True           4.00         14.00
5       Bruna     23    NaN     False            NaN           NaN
6        Dara     21    7.0      True           2.80          9.80
7      Carlos     19    6.0      True           2.40          8.40
8       Alice     35    5.6     False           2.24          7.84
9       Vitor     28    NaN     False            NaN           NaN
10     Daniel     21    NaN     False            NaN           NaN
11       Igor     24    4.5     False           1.80          6.30
12  Sthefanie     26    9.5      True           3.80         13.30
13      Mirla     25    9.0      True           3.60         12.60
14      Paulo     37    NaN     False            NaN           NaN
15     Mylena     29    7.0      True           2.80          9.80
16      Lucas     33    NaN     False            NaN           NaN
17      Nadia     34    8.0      True           3.20         11.20

In [27]:
#3) Como houve uma pontuação extra, alguns alunos que não tinham sido aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna chamada "Aprovado_final" com os seguintes valores: 
# True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6); 
# False: caso o aluno esteja reprovado (nota final deve ser menor que 6).
df_alunos['Aprovado_final'] = df_alunos['Notas_finais'].apply(lambda x: True if x >= 6 else False)
df_alunos

,Nome,Idade,Notas,Aprovado,Pontos_extras,Notas_finais,Aprovado_final
0,Ary,20,7.5,True,3.00,10.50,True
1,Ana,18,NaN,False,NaN,NaN,False
2,Cátia,27,2.5,False,1.00,3.50,False
3,Denis,18,5.0,False,2.00,7.00,True
4,Beto,21,10.0,True,4.00,14.00,True
5,Bruna,23,NaN,False,NaN,NaN,False
6,Dara,21,7.0,True,2.80,9.80,True
7,Carlos,19,6.0,True,2.40,8.40,True
8,Alice,35,5.6,False,2.24,7.84,True
9,Vitor,28,NaN,False,NaN,NaN,False
10,Daniel,21,NaN,False,NaN,NaN,False
11,Igor,24,4.5,False,1.80,6.30,True
12,Sthefanie,26,9.5,True,3.80,13.30,True
13,Mirla,25,9.0,True,3.60,12.60,True
14,Paulo,37,NaN,False,NaN,NaN,False
15,Mylena,29,7.0,True,2.80,9.80,True
16,Lucas,33,NaN,False,NaN,NaN,False
17,Nadia,34,8.0,True,3.20,11.20,True

In [28]:
#4) Faça uma seleção e verifique quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras.
seleção = df_alunos['Aprovado'] != df_alunos['Aprovado_final']
df_alunos[seleção]

     Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais  Aprovado_final
3   Denis     18    5.0     False           2.00          7.00            True
8   Alice     35    5.6     False           2.24          7.84            True
11   Igor     24    4.5     False           1.80          6.30            True

Nessa aula, você aprendeu a:

    -> Gerar colunas numéricas;
    -> Inserir colunas categóricas;
    -> Definir colunas binárias;
    -> Realizar operações entre colunas;
    -> Utilizar o método apply;
    -> Criar funções lambda.